version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CONNECTION_STRING=mongodb://database:27017/ePhoneShop
    depends_on:
      - database

  database:
    image: mongo:6
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
